In [1]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [2]:
len?

In [3]:
L = [1,2,3,4]
L.insert?

In [4]:
L?

In [5]:
#Initializing Docstring
def square(a):
    """Returns square of a number"""
    return a**2

In [6]:
square?

In [7]:
# * character matches any string
*Warning?

In [8]:
# show us execution time
%timeit L = [n ** 2 for n in range(1000)]

453 µs ± 8.85 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [13]:
import math

a = math.sin(3)
print(a)
b = math.cos(3)
print(b)

0.1411200080598672
-0.9899924966004454


In [11]:
#prints all the input lines
print(In)

['', 'help(len)', "get_ipython().run_line_magic('pinfo', 'len')", "L = [1,2,3,4]\nget_ipython().run_line_magic('pinfo', 'L.insert')", "get_ipython().run_line_magic('pinfo', 'L')", 'def square(a):\n    """Returns square of a number"""\n    return a**2', "get_ipython().run_line_magic('pinfo', 'square')", "get_ipython().run_line_magic('psearch', '*Warning')", "# show us execution time\nget_ipython().run_line_magic('timeit', 'L = [n ** 2 for n in range(1000)]')", 'import math\n\nmath.sin(3)\nmath.cos(3)', 'import math\n\na = math.sin(3)\nb = math.cos(3)', 'print(In)']


In [14]:
#prints all the output
print(Out)

{9: -0.9899924966004454}


In [15]:
print(_)

-0.9899924966004454


In [19]:
math.sin(3)

0.1411200080598672

In [20]:
math.cos(3)

-0.9899924966004454

In [21]:
# prints last output
print(_)

print(__) # prints 2nd last output

-0.9899924966004454
0.1411200080598672


In [23]:
%history -n 1-4

   1: help(len)
   2: len?
   3:
L = [1,2,3,4]
L.insert?
   4: L?


In [24]:
%%time # use double percentage for multiple line
 total = 0
 for i in range(1000):
    for j in range(1000):
        total += i * (-1) ** j

Wall time: 652 ms


In [25]:
import numpy as np

np.__version__

'1.16.4'

In [26]:
np.array([1,2,3,4])# data type must be same

array([1, 2, 3, 4])

In [27]:
np.array([2.5,2,4,5])# auto converts to float

array([2.5, 2. , 4. , 5. ])

In [28]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [30]:
np.ones((3,5), dtype=int) # np.ones((row, column), data-type)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [31]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [32]:
np.linspace(0, 1, 5) # divide 0 to 1 in 5 even portions

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [33]:
np.random.random((3, 3))

array([[0.24379623, 0.2001754 , 0.20242453],
       [0.6721594 , 0.84966937, 0.27187971],
       [0.6007538 , 0.22393616, 0.56320153]])

In [34]:
np.random.normal(0, 1, (3, 3)) #3 x 3 array with mean 0 and standard deviation 1

array([[ 0.18176495, -0.54397179,  1.3705772 ],
       [-1.38476773,  0.4752751 ,  1.36348453],
       [ 1.42276331, -2.43072721, -1.19121998]])

In [35]:
np.random.randint(0, 10, (3, 3)) # 3 x 3 array of interval [0, 10]

array([[9, 8, 8],
       [7, 1, 6],
       [5, 5, 4]])

In [36]:
np.eye(3) # identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
import numpy as np

np.random.seed(0) # seed for reproducibility

x1 = np.random.randint(10, size=6) # One-dimensional array
print(x1)
print("---------")
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
print(x2)
print("---------")
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array
print(x3)
print("---------")

[5 0 3 3 7 9]
---------
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
---------
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
---------


In [38]:
print(x1.ndim, x1.shape, x1.size)
print(x2.ndim, x2.shape, x2.size)
print(x3.ndim, x3.shape, x3.size)

1 (6,) 6
2 (3, 4) 12
3 (3, 4, 5) 60


In [41]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
x[:5]

array([0, 1, 2, 3, 4])

In [43]:
x[5:]

array([5, 6, 7, 8, 9])

In [44]:
x[4:7]

array([4, 5, 6])

In [45]:
x[::2]

array([0, 2, 4, 6, 8])

In [46]:
x[1::2]

array([1, 3, 5, 7, 9])

In [47]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [48]:
x[5::-2]

array([5, 3, 1])

In [49]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [50]:
x2[:2, :3] # 2 rows 3 columns

array([[3, 5, 2],
       [7, 6, 8]])

In [51]:
x2[:3, ::2]

array([[3, 2],
       [7, 8],
       [1, 7]])

In [52]:
x2[::-1, ::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [53]:
x2[:, 0]

array([3, 7, 1])

In [55]:
x2[0, :]

array([3, 5, 2, 4])

In [56]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [58]:
grid = np.array([[1, 2, 3],[4, 5, 6]])
np.concatenate([grid,grid]) # arrays must have same dimension

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [59]:
np.vstack([x,grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [62]:
y = np.array([[8],[9]])
np.hstack([grid,y])

array([[1, 2, 3, 8],
       [4, 5, 6, 9]])

In [63]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])